### ISSUE TITLE
Game crashes when rubidium extras is pressent (1.20.1)

### ISSUE THREAD

**Issue by FelixDaemonWox** [txnimc/SodiumOptionsAPI#6]
when the mod sodium options api is pressent with embedium/rubidium extras the game crashes at loading

minecraft 1.20.1 forge 47.3.10

latest versions of Embedium, Sodium options api and embedium/rubidium extras

here's the console output at the crash (there's no crash or log since the game crashes immediately)
> `Using default game log configuration client-1.12.xml (outputs XML)
ModLauncher running: args [--username, FelixBluWox, --version, forge-47.3.5, --gameDir, C:\Users\felix\curseforge\minecraft\Instances\tests, --assetsDir, C:\Users\felix\curseforge\minecraft\Install\assets, --assetIndex, 5, --uuid, b523bc4080be4d9793f28d27e3d9f049, --accessToken, [], --clientId, [], --xuid, [], --userType, msa, --versionType, release, --width, 1024, --height, 768, --quickPlayPath, C:\Users\felix\curseforge\minecraft\Install\quickPlay\java\1727828372286.json, --launchTarget, forgeclient, --fml.forgeVersion, 47.3.5, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.8 by Microsoft; OS Windows 10 arch amd64 version 10.0
Loading ImmediateWindowProvider fmlearlywindow
Trying GL version 4.6
Requested GL version 4.6 got version 4.6
SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/felix/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23100!/ Service=ModLauncher Env=CLIENT
GL info: Radeon RX550/550 Series GL version 4.6.0 Core Profile Context 22.11.2.221130, ATI Technologies Inc.
Found mod file embeddium-0.3.31+mc1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\felix\curseforge\minecraft\Instances\tests\mods}
Found mod file rubidium-extra-0.5.4.3+mc1.20.1-build.121.jar of type MOD with provider {mods folder locator at C:\Users\felix\curseforge\minecraft\Instances\tests\mods}
Found mod file sodiumoptionsapi-forge-1.0.2-1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\felix\curseforge\minecraft\Instances\tests\mods}
Mod file C:\Users\felix\curseforge\minecraft\Install\libraries\net\minecraftforge\fmlcore\1.20.1-47.3.5\fmlcore-1.20.1-47.3.5.jar is missing mods.toml file
Mod file C:\Users\felix\curseforge\minecraft\Install\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.3.5\javafmllanguage-1.20.1-47.3.5.jar is missing mods.toml file
Mod file C:\Users\felix\curseforge\minecraft\Install\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.3.5\lowcodelanguage-1.20.1-47.3.5.jar is missing mods.toml file
Mod file C:\Users\felix\curseforge\minecraft\Install\libraries\net\minecraftforge\mclanguage\1.20.1-47.3.5\mclanguage-1.20.1-47.3.5.jar is missing mods.toml file
Found mod file fmlcore-1.20.1-47.3.5.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@79a1728c
Found mod file javafmllanguage-1.20.1-47.3.5.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@79a1728c
Found mod file lowcodelanguage-1.20.1-47.3.5.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@79a1728c
Found mod file mclanguage-1.20.1-47.3.5.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@79a1728c
Found mod file client-1.20.1-20230612.114412-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@79a1728c
Found mod file forge-1.20.1-47.3.5-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@79a1728c
Found 4 dependencies adding them to mods collection
Found mod file NanoLiveConfig-1.2.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@238acd0b
Found mod file mixinextras-forge-0.4.1.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@238acd0b
Found mod file fabric-api-base-0.4.31+ef105b4977.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@238acd0b
Found mod file MixinExtras-0.4.1.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@238acd0b
Compatibility level set to JAVA_17
Launching target 'forgeclient' with arguments [--version, forge-47.3.5, --gameDir, C:\Users\felix\curseforge\minecraft\Instances\tests, --assetsDir, C:\Users\felix\curseforge\minecraft\Install\assets, --uuid, b523bc4080be4d9793f28d27e3d9f049, --username, FelixBluWox, --assetIndex, 5, --accessToken, [], --clientId, [], --xuid, [], --userType, msa, --versionType, release, --width, 1024, --height, 768, --quickPlayPath, C:\Users\felix\curseforge\minecraft\Install\quickPlay\java\1727828372286.json]
Loaded configuration file for Embeddium: 52 options available, 0 override(s) found
Searching for graphics cards...
Found graphics card: GraphicsAdapterInfo[vendor=UNKNOWN, name=LuminonCore IDDCX Adapter, version=DriverVersion=1.0.2018.1204]
Found graphics card: GraphicsAdapterInfo[vendor=AMD, name=Radeon RX550/550 Series, version=DriverVersion=31.0.12029.10015]
Exception in thread "main" java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/fabricmc/loader/api/FabricLoader
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/loader/api/FabricLoader
	at TRANSFORMER/NanoLiveConfig@1.2.0/net.caffeinemc.caffeineconfig.CaffeineConfig.fabric$applyModOverrides(CaffeineConfig.java:253)
	at TRANSFORMER/NanoLiveConfig@1.2.0/net.caffeinemc.caffeineconfig.CaffeineConfig.applyModOverrides(CaffeineConfig.java:207)
	at TRANSFORMER/NanoLiveConfig@1.2.0/net.caffeinemc.caffeineconfig.CaffeineConfig$Builder.build(CaffeineConfig.java:540)
	at TRANSFORMER/embeddium_extra@0.5.4.3+mc1.20.1-build.121/me.flashyreese.mods.sodiumextra.client.SodiumExtraClientMod.mixinConfig(SodiumExtraClientMod.java:63)
	at TRANSFORMER/embeddium_extra@0.5.4.3+mc1.20.1-build.121/me.flashyreese.mods.sodiumextra.mixin.SodiumExtraMixinConfigPlugin.createConfig(SodiumExtraMixinConfigPlugin.java:13)
	at TRANSFORMER/NanoLiveConfig@1.2.0/net.caffeinemc.caffeineconfig.AbstractCaffeineConfigMixinPlugin.onLoad(AbstractCaffeineConfigMixinPlugin.java:16)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:707)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:637)
	at java.base/java.lang.Class.forName(Class.java:545)
	at MC-BOOTSTRAP/fmlearlydisplay@1.20.1-47.3.5/net.minecraftforge.fml.earlydisplay.DisplayWindow.lambda$updateModuleReads$14(DisplayWindow.java:601)
	at java.base/java.util.Optional.map(Optional.java:260)
	at MC-BOOTSTRAP/fmlearlydisplay@1.20.1-47.3.5/net.minecraftforge.fml.earlydisplay.DisplayWindow.updateModuleReads(DisplayWindow.java:601)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.5/net.minecraftforge.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:71)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.5/net.minecraftforge.fml.loading.FMLLoader.beforeStart(FMLLoader.java:207)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.5/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:92)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.api.FabricLoader
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 39 more`

**Comment by nthxny** [comment]
this is not coming from this mod. Something in rubidium extras is failing.
